### ISSUE TITLE
SQL error after installation: Base table or view not found

### ISSUE THREAD

**Issue by 01Kuzma** [wintercms/wn-sitemap-plugin#12]
Hi!
I just installed the plugin with composer: `composer require winter/wn-pages-plugin`
After the installation, the plugin is not displayed in the plugin list in the backend and not in the list `artisan plugin:list`

The files are present in the `winter\sitemap\` folder
Also menu item has appeared in the backend, accessing it the error is generated:
"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'MY_DB_PREFIX.winter_sitemap_definitions' doesn't exist (SQL: select * from `winter_sitemap_definitions` where (`theme` = MY_THEME_NAME) limit 1)" on line 760 of C:\laragon\www\winter3\vendor\laravel\framework\src\Illuminate\Database\Connection.php

**Comment by mjauvin** [comment]
You need to run "php artisan migrate" after composer installs
