### ISSUE TITLE
Listing records Builder in sitemap.xml

### ISSUE THREAD

**Issue by Webmasters-WPNGO** [wintercms/wn-sitemap-plugin#13]
Added output of records via Builder List on the page. Can I add them all to sitemap.xml?

**Comment by bennothommo** [comment]
@WebProviderNGO not directly through the Builder plugin. You would have to create a plugin that listens for the `page.menuItem` events that are provided in the [Pages and Sitemap](https://github.com/wintercms/wn-pages-plugin/blob/main/docs/documentation.md#creating-new-menu-item-types) plugins and register a new type of navigation item from the records you created in your Builder-built plugin.
