### ISSUE TITLE
Sitemap error

### ISSUE THREAD

**Issue by Artful-dodger** [wintercms/wn-sitemap-plugin#16]
i am getting this error whilst trying to generate sitemap file my version of wintercms is 1.2.4 the error  I am getting is  /vendor/laravel/serializable-closure/src/Serializers/Signed.php line 83. I tried composer update  and composer upgrade laravel/framework --with-all-dependencies but still no luck

**Comment by mjauvin** [comment]
It would be helpful to see the code that generates the error... How do you "generate sitemap file" ?

**Comment by Artful-dodger** [comment]
I am using version 2.0.0 I have just found a solution but not sure why is happened, I tried php artisan route:clear , that sorted the is sue any idea what may have cause this I have checked through my log files nothing obvious though. thank you for your prompt
reply

**Comment by mjauvin** [comment]
No idea.
Why aren't you using the latest version (2.0.2) ?

**Comment by Artful-dodger** [comment]
I just used composer to install
Sent from my iPhone

On 3 Mar 2024, at 13:14, Marc Jauvin ***@***.***> wrote:

﻿

No idea.
Why aren't you using the latest version (2.0.2) ?

**Comment by LukeTowers** [comment]
That would make sense, if your routes were cached then this plugin's routes wouldn't have been able to be picked up. Perhaps that's something that we could / should include in the default composer scripts of the main repo @mjauvin?

**Comment by mjauvin** [comment]
@LukeTowers you mean add this?
```yaml
"post-update-cmd": [
    ...
    "@php artisan route:clear"
]
```
