### ISSUE TITLE
Changes in sitemap cant save

### ISSUE THREAD

**Issue by Pascualsolutions** [wintercms/wn-sitemap-plugin#20]
Hi, 
I have problem after install sitemap i cant save changes. Example i add some pages in sitemap but after save nothing happen the list is empty.
Can u check please.
Alex

**Comment by mjauvin** [comment]
What version are you using?

**Comment by Pascualsolutions** [comment]
Im on latest v1.2.7. On older version everithing working fine.

I  have just blog plugin and sitemap.

Thanks for fast response.

Alex

**Comment by mjauvin** [comment]
Ok, but what version of Sitemap plugin ?

**Comment by Pascualsolutions** [comment]
The version is 	2.0.2

**Comment by LukeTowers** [comment]
@Pascualsolutions run `composer update`, the fixes hadn't been released as a new version yet. Thanks for reporting the issue!

**Comment by Pascualsolutions** [comment]
Works great.
Thank you for fast support.
Best regards
