### ISSUE TITLE
Add hreflang attribute to sitemap url entries

### ISSUE THREAD

**Issue by der-On** [wintercms/wn-sitemap-plugin#5]
For multilingual sites adding the `hreflang` attribute is required for correct SEO.

I would suggest that the `locale` property of a menu item should be used for that. If not present no `hreflang` attribute should be attached.

Problems to solve:

Automaticly add locale versions of static pages if the translate plugin is present and has more then one active locale.

I could provide a PR for that.

**Comment by bennothommo** [comment]
@der-On just curious - is there any benefit to the `hreflang` attribute being in the sitemap links as opposed to a meta tag on the pages themselves? The meta tag is something that can be done in the theme (or perhaps through the Translate plugin as a component).

**Comment by der-On** [comment]
> @der-On just curious - is there any benefit to the `hreflang` attribute being in the sitemap links as opposed to a meta tag on the pages themselves? The meta tag is something that can be done in the theme (or perhaps through the Translate plugin as a component).

This would require including all locale variants of a page/url in the sitemap. The current implementation does not do this, but only lists the canonical urls of pages without a language prefix. Then the browser/session decides which language to display/redirect to. Not sure about how search engines do this. Maybe they index pages by mimicing various preferred languages?

I'm no SEO expert but just read that `hreflang` is a best practise for multilingual sitemaps.

Maybe I'm opening a can of worms here. I'll try to ask a SEO expert about this.

**Comment by der-On** [comment]
If including this in the core of the plugin is out of scope (which I can understand) adding an event to extend the generated sitemap would be good. That way one can add extra information as required for a use case.

**Comment by LukeTowers** [comment]
Ideally the Winter.Translate plugin should be able to hook into this plugin to add the appropriate multilingual configuration automatically.

**Comment by mjauvin** [comment]
Yes, I had to create this plugin in the past because I proposed adding an event and it didn't get accepted.

**Comment by mjauvin** [comment]
Go for it @der-On !

**Comment by LukeTowers** [comment]
@mjauvin do you have a link to your original proposal?

**Comment by mjauvin** [comment]
@LukeTowers https://github.com/rainlab/sitemap-plugin/pull/74

**Comment by der-On** [comment]
@LukeTowers Merged current main branch into your wip and made some minor adjustments https://github.com/wintercms/wn-sitemap-plugin/pull/6
Also tested it with my use case and it worked very well.

**Comment by LukeTowers** [comment]
@der-On are you able to also make a PR to the translate plugin so that it can hook into these events when present and automatically make the sitemap support the localized URLs available on the site?

**Comment by der-On** [comment]
@LukeTowers I can do.
