### ISSUE TITLE
Could not scan for classes error

### ISSUE THREAD

**Issue by pierzo** [wintercms/wn-sitemap-plugin#9]
Hi, when I try to install on composer ver 2.3.7 I get 

In ClassMapGenerator.php line 74:
Could not scan for classes inside "tests/fixtures/backend/models/UserFixture.php" which does not appear to be a file nor a folder

**Comment by bennothommo** [comment]
Your `composer.json` file might be out of date if you are installing Winter v1.2.x.

You'll need to remove the following lines:

```
    "autoload-dev": {
        "classmap": [
            "tests/concerns/InteractsWithAuthentication.php",
            "tests/fixtures/backend/models/UserFixture.php",
            "tests/TestCase.php",
            "tests/PluginTestCase.php"
        ]
    },
```

**Comment by bennothommo** [comment]
Run `php artisan winter:up`.
